export const mockEvents = [
  // January 2026 Events
  {
    date: "2026-01-02",
    ticker: "AAPL",
    eventType: "EARNINGS",
    title: "Earnings Report Q4 2024",
    time: "After Market",
    impact: "High",
  },
  {
    date: "2026-01-02",
    ticker: "MSFT",
    eventType: "RESULTS",
    title: "Results Conference Call",
    time: "09:00 EST",
    impact: "Medium",
  },
  {
    date: "2026-01-05",
    ticker: "TSLA",
    eventType: "NEWS",
    title: "New Factory Announcement",
    time: "14:30 EST",
    impact: "High",
  },
  {
    date: "2026-01-05",
    ticker: "GOOGL",
    eventType: "EARNINGS",
    title: "Earnings Guidance Update",
    time: "After Market",
    impact: "High",
  },
  {
    date: "2026-01-08",
    ticker: "AMZN",
    eventType: "RESULTS",
    title: "Results Q4 2024 Holiday Sales",
    time: "08:30 EST",
    impact: "High",
  },
  {
    date: "2026-01-10",
    ticker: "NVDA",
    eventType: "NEWS",
    title: "New GPU Launch Event",
    time: "10:00 EST",
    impact: "Medium",
  },
  {
    date: "2026-01-10",
    ticker: "META",
    eventType: "EARNINGS",
    title: "Earnings Call Q4 2024",
    time: "After Market",
    impact: "High",
  },
  {
    date: "2026-01-15",
    ticker: "NFLX",
    eventType: "EARNINGS",
    title: "Earnings Report Subscriber Growth",
    time: "After Market",
    impact: "High",
  },
  {
    date: "2026-01-15",
    ticker: "JPM",
    eventType: "RESULTS",
    title: "Results Banking Q4 Performance",
    time: "Pre-Market",
    impact: "Medium",
  },
  {
    date: "2026-01-17",
    ticker: "BAC",
    eventType: "RESULTS",
    title: "Results Financial Overview",
    time: "07:00 EST",
    impact: "Medium",
  },
  {
    date: "2026-01-20",
    ticker: "INTC",
    eventType: "NEWS",
    title: "New Chip Manufacturing Deal",
    time: "11:00 EST",
    impact: "Low",
  },
  {
    date: "2026-01-22",
    ticker: "AMD",
    eventType: "EARNINGS",
    title: "Earnings Report Q4 2024",
    time: "After Market",
    impact: "High",
  },
  {
    date: "2026-01-22",
    ticker: "QCOM",
    eventType: "RESULTS",
    title: "Results Smartphone Chip Sales",
    time: "16:00 EST",
    impact: "Medium",
  },
  {
    date: "2026-01-23",
    ticker: "CSCO",
    eventType: "EARNINGS",
    title: "Earnings Networking Equipment",
    time: "After Market",
    impact: "Medium",
  },
  {
    date: "2026-01-23",
    ticker: "CRM",
    eventType: "NEWS",
    title: "New AI Feature Launch",
    time: "13:00 EST",
    impact: "Low",
  },
  {
    date: "2026-01-25",
    ticker: "IBM",
    eventType: "RESULTS",
    title: "Results Cloud Revenue Growth",
    time: "Pre-Market",
    impact: "Low",
  },
  {
    date: "2026-01-28",
    ticker: "ORCL",
    eventType: "EARNINGS",
    title: "Earnings Database Revenue",
    time: "After Market",
    impact: "Medium",
  },
  {
    date: "2026-01-29",
    ticker: "V",
    eventType: "RESULTS",
    title: "Results Payment Volume Update",
    time: "09:30 EST",
    impact: "High",
  },
  {
    date: "2026-01-30",
    ticker: "MA",
    eventType: "RESULTS",
    title: "Results Transaction Processing",
    time: "08:00 EST",
    impact: "High",
  },

  // December 2024 Events
  {
    date: "2024-12-03",
    ticker: "SNOW",
    eventType: "EARNINGS",
    title: "Earnings Cloud Growth Report",
    time: "After Market",
    impact: "Medium",
  },
  {
    date: "2024-12-05",
    ticker: "UBER",
    eventType: "RESULTS",
    title: "Results Ride Volume Update",
    time: "Pre-Market",
    impact: "Medium",
  },
  {
    date: "2024-12-10",
    ticker: "DIS",
    eventType: "NEWS",
    title: "New Streaming Content Deal",
    time: "15:00 EST",
    impact: "Low",
  },
  {
    date: "2024-12-12",
    ticker: "NKE",
    eventType: "EARNINGS",
    title: "Earnings Holiday Season Sales",
    time: "After Market",
    impact: "High",
  },
  {
    date: "2024-12-18",
    ticker: "COST",
    eventType: "RESULTS",
    title: "Results Membership Numbers",
    time: "After Market",
    impact: "Medium",
  },

  // February 2026 Events
  {
    date: "2026-02-03",
    ticker: "PYPL",
    eventType: "EARNINGS",
    title: "Earnings Payment Processing",
    time: "After Market",
    impact: "Medium",
  },
  {
    date: "2026-02-05",
    ticker: "SPOT",
    eventType: "RESULTS",
    title: "Results Subscriber Growth Q4",
    time: "Pre-Market",
    impact: "High",
  },
  {
    date: "2026-02-10",
    ticker: "SHOP",
    eventType: "EARNINGS",
    title: "Earnings E-commerce Platform",
    time: "After Market",
    impact: "Medium",
  },
  {
    date: "2026-02-14",
    ticker: "SQ",
    eventType: "NEWS",
    title: "New Payment Feature Launch",
    time: "10:00 EST",
    impact: "Low",
  },
  {
    date: "2026-02-18",
    ticker: "ZM",
    eventType: "EARNINGS",
    title: "Earnings Enterprise Growth",
    time: "After Market",
    impact: "Medium",
  },
  {
    date: "2026-02-20",
    ticker: "DOCU",
    eventType: "RESULTS",
    title: "Results Digital Signature",
    time: "16:00 EST",
    impact: "Low",
  },
  {
    date: "2026-02-25",
    ticker: "TWLO",
    eventType: "EARNINGS",
    title: "Earnings Communications API",
    time: "After Market",
    impact: "Medium",
  },
];